# Please see doc page for any information on what the parameters do!
# DON'T FORGET TO CHANGE SBATCH COMMANDS!!!!!!
# Simulation
export RES=24
export GAM=2
export MESHX=16
export MESHY=12
export N=192
export C=1
export RA=5
export PR=-1.5
export SIM_TIME=200
export STEPPER=RK222
export CFL_SAFETY=0.25
export CFL_THRESHOLD=0.1
export CFL_CADENCE=2
export DT=0.0005
export LX=2
export LY=2
export A_FREQ=0.005
export STATE_FREQ=1800
export SNAPS_FREQ=0.0166666667
export START_TIME=0
export IC=1
export TMP=True
export PARA=virtual


# You must comment out the following if you don't want that option. The value doesn't matter.
export SNAPSHOTS=1
export CFL=1


# Post process
export AVG_TIME=2500
export POWER_YMIN=-18
export POWER_YMAX=0
export VMINS="-6,-1,-1,-4"
export VMAXS="3,4,4,3"
export TMINS="-11,1,-6,-9"
export TMAXS="3,3,4,3"
export MVORT=15
export MVERT=15

export FPS=60


# Shell
export SETUP_PATH="$SCRATCH/rbc_scripts/setup.sh"
export WORKFLOW_PATH="$SCRATCH/rbc_scripts/workflow.sh"
export SCRIPTS_PATH="$SCRATCH/rbc_scripts"
export SCRIPTS_3D="$SCRATCH/rbc_scripts/3d"
export ENV_PATH="$SCRATCH/ded3"
export VIS_ENV_PATH="$SCRATCH/ded3_vis"
export BASE="$PWD"



#!/bin/bash

#SBATCH --output=job_sim.out
#SBATCH --time=11:59:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=192
#SBATCH --mem=0
#SBATCH --job-name=ra5pr3e-2_96
#SBATCH --account=def-goluskin
# Tells SLURM to send the SIGUSR1 signal 1800 seconds (30 min, or ~ 3Tb of transfer) before end of the time limit, or 5 min if no slurm_tmpdir.
#SBATCH --signal=B:SIGUSR1@1800